mod conflict;
mod copy;
pub(crate) mod engine;
pub(crate) mod lease;
pub(crate) mod model;
mod peer;
pub(crate) mod preview;
pub(crate) mod runtime;
mod scan;
pub use model::{Choice, Conflict, Direction, Status, Transfer};
pub type Progress = std::sync::Arc<dyn Fn(Transfer) + Send + Sync>;
